version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydatabase
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - app-network
    volumes:
      - .:/app

networks:
  app-network:

volumes:
  db-data:
